### ISSUE TITLE
Noob: Permissions at record level

### ISSUE THREAD

**Issue by flowt-au** [automerge/automerge-classic#146]
Hi. I am completely new to these ideas. I watched Martin's video about making servers optional and am really interested for my project.

One topic I am interested in, and cant find any discussion on, is how to manage record level permissions. Take a hypothetical where an enterprise app has employees:
 
Fred (an admin) has full CRUD permission on all employee details (name, email, phone, location, role, salary, dob, etc)
Jane can update only a sub-set of employee data (eg change their current location and phone ext in the building)
Sally can only read the list of employee names and phone extentions

In broad terms, how would one go about enforcing permissions (that might change over time)? We obviously can't replicate sensitive info like the Permission store across user devices but it should instead remain centralised somewhere(?) And we would need a way to revoke (delete) certain employee data where a given user can no longer see data that once they could. eg Fred gets demoted to the same access as Jane, for example. Fred should now not have any sensitive employee data on his computer, but still has a sub set. 

I know this is a contrived example but I have a number of similar scenarios in my current project where people can see only certain parts of given data sets (employee data being just one). With a centralised server and no local storage of course that can be done. So, are these situations outside the possibility for this "server optional" model?

Thanks again. Fascinating.

**Comment by pvh** [comment]
Howdy! There are a few ways to think about this problem, but the heart of it is to understand that clients can read and write to any data you give them. As a result, you could consider that you might create a CRDT per-client and update that over time. Perhaps instead of having clients make changes to data you could have them write change requests into the CRDT. The server could simply write truth over-top of any changes it rejects... you'd have to give it some thought.

In general, if you're starting to internalize the world of CRDTS I'd encourage you think less about "permission" and more about "attention" and "visibility". Does the server pay attention to the writes the client makes? Does the client see everything?

Remember that anything you share stays shared...

Overall, I think it could work but I'm not sure it's where I'd start my CRDT lifestyle. :) Still, best of luck!

**Comment by flowt-au** [comment]
Thanks! I was running a thought experiment first! How would I use CRDTs in my current project?

And, I get that it isn't an all-or-nothing so start with the part that handles something like "chat". :-)

Thanks for your response. It was helpful in getting clarity. Like the microservices world (which I see synergies with here) I guess design patterns will emerge over time.

**Comment by schrepfler** [comment]
Definitely not a noob question 😀 this is basic capabilities and design.

**Comment by flowt-au** [comment]
Thanks. I was also thinking that a "chat" application already deals with immutable objects (each message, typically sent with no later edit) but a messaging process where users could edit their own messages after sending would definitely be in the realm of CRDTs so a good candidate for an entry level exploration without significant "permission" / "visibility" issues, I think. Time will tell! ;-)

**Comment by flowt-au** [comment]
Thanks. It wont be soon but I am intrigued enough to have a play as soon as I can. :-)

**Comment by bkniffler** [comment]
I find it interesting to think about permissions in a CRDT scenario. As one logs in to an app, you could fetch your permissions. The app might then restrict what actions you can perform. As soon as you go online and your local changes are synced, the server needs to verify if your actions really correspond to whatever permissions you have.

For this, in an application where multiple users have access to the same machine, I'd love to be able to locally sign a change and add the signature to the documents history. I thought about using commit messages for that purpose, though these need to be specified upfront, before the change. A way to add metadata to changes would be super cool.
